logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG


spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/loyaltyoneinterview
    username: loyalty_user
    password: a@1234
